replicaCount: 1

image:
  repository: abayisenga/banking-customer-service
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred

service:
  name: customer-service
  type: ClusterIP
  port: 8050

config:
  serverUrl: "http://config-server:8888"

eureka:
  url: "http://discovery-server:8761/eureka/"

database:
  host: "postgres"
  port: "5432"
  name: "customer"
  username: "postgres"
  password: "Password123!"

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "250m"

env:
  javaOpts: "-Xms128m -Xmx256m"

initContainers:
  waitForConfigServer: true
  waitForDiscovery: true

extraEnv: []
