replicaCount: 1

image:
  repository: abayisenga/banking-customer-service
  tag: "97b262f"

database:
  host: "postgres"
  port: "5432"
  name: "customer"
  username: "postgres"
  password: "Password123!"

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "250m"
